# theme: jekyll-theme-slate
remote_theme: maiconpinto/jekyll-theme-prettydocs

title: Kikkoman
description: Free static blog hosting via Github?

# tell it to use kramdown so that I can get a Table of Content "macro"
markdown: kramdown

# define "theSetup" as a collection so that it will render those pages
collections:
  theSetup :
    output: true
