#### Tech things
# tell it to use kramdown so that I can get a Table of Content "macro"
markdown: kramdown

#### Standard Things
title: Kikkoman.org
# suppress the description by haveing it be blank?
description: Milo's Stuff

#### Theme and Theme specific settings
theme: jekyll-theme-slate
show_downloads: false


#### Kikkoman specific settings
# define "theSetup" as a collection so that it will render those pages
collections:
  theSetup :
    output: true
  til :
    output : true

## Configuring Prose ala
## https://blog.webjeda.com/edit-posts-jekyll/ started with 
## edited based on https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  siteurl: 'https://kikkoman.org'
  # I don't know what this does
  # relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  
  # Pro-Tip do not make your media dir start with an underscore ala _images
  #  Jekyll will treat that as a special dir / non of the things in that dir will
  #  be in visible in the output
  media: 'media'
  
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
    _theSetup:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "hook"
        field:
          element: "text"
          label: "What is the hook?"
          value: ""
    _til:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "hook"
        field:
          element: "text"
          label: "What is the hook?"
          value: ""
