#### Tech things
# tell it to use kramdown so that I can get a Table of Content "macro"
markdown: kramdown

#### Standard Things
title: Kikkoman
description: Free static blog hosting via Github?

#### Theme and Theme specific settings
theme: jekyll-theme-slate
show_downloads: false


#### Kikkoman specific settings
# define "theSetup" as a collection so that it will render those pages
collections:
  theSetup :
    output: true

## Configuring Prose ala
## https://blog.webjeda.com/edit-posts-jekyll/ started with 
## edited based on https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  siteurl: 'https://milosimpson.github.io/'
  # don't understand what this does
  #relativeLinks: 'http://prose.github.io/starter/links.jsonp'

  # tell it where media files should be
  #  should not be a dir like "_media" as that tells Jekyll it is a special dir
  #  that should not be visible on the output side
  media: 'media'
  
  ignore:
    - /_layouts
    - /_includes

  metadata:
    # think this allows me to configure defaults prose to use for new files
    # in each of the "sections"
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
    _theSetup:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "hook"
        field:
          element: "text"
          label: "What is the hook?"
          value: ""
